#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "service.pb.h"

namespace KeyWord
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void KeyWord(reqInfo *request, respInfo *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using KeyWordDone = std::function<void (respInfo *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void KeyWord(const reqInfo *req, KeyWordDone done);
	void KeyWord(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> async_KeyWord(const reqInfo *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_KeyWord_task(KeyWordDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void KeyWord(const reqInfo *req, KeyWordDone done);
	void KeyWord(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> async_KeyWord(const reqInfo *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_KeyWord_task(KeyWordDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void KeyWord(const reqInfo *req, KeyWordDone done);
	void KeyWord(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> async_KeyWord(const reqInfo *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_KeyWord_task(KeyWordDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void KeyWord(const reqInfo *req, KeyWordDone done);
	void KeyWord(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> async_KeyWord(const reqInfo *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_KeyWord_task(KeyWordDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void KeyWord(const reqInfo *req, KeyWordDone done);
	void KeyWord(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> async_KeyWord(const reqInfo *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_KeyWord_task(KeyWordDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("KeyWord")
{
	this->srpc::RPCService::add_method("KeyWord",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::KeyWord);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("KeyWord")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("KeyWord")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::KeyWord(const reqInfo *req, KeyWordDone done)
{
	auto *task = this->create_rpc_client_task("KeyWord", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::KeyWord(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_KeyWord(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> SRPCClient::async_KeyWord(const reqInfo *req)
{
	using RESULT = std::pair<respInfo, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<respInfo>("KeyWord", srpc::RPCAsyncFutureCallback<respInfo>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_KeyWord_task(KeyWordDone done)
{
	return this->create_rpc_client_task("KeyWord", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("KeyWord")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("KeyWord")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::KeyWord(const reqInfo *req, KeyWordDone done)
{
	auto *task = this->create_rpc_client_task("KeyWord", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::KeyWord(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_KeyWord(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> SRPCHttpClient::async_KeyWord(const reqInfo *req)
{
	using RESULT = std::pair<respInfo, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<respInfo>("KeyWord", srpc::RPCAsyncFutureCallback<respInfo>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_KeyWord_task(KeyWordDone done)
{
	return this->create_rpc_client_task("KeyWord", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("KeyWord")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("KeyWord")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::KeyWord(const reqInfo *req, KeyWordDone done)
{
	auto *task = this->create_rpc_client_task("KeyWord", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::KeyWord(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_KeyWord(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> BRPCClient::async_KeyWord(const reqInfo *req)
{
	using RESULT = std::pair<respInfo, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<respInfo>("KeyWord", srpc::RPCAsyncFutureCallback<respInfo>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_KeyWord_task(KeyWordDone done)
{
	return this->create_rpc_client_task("KeyWord", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("KeyWord")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("KeyWord")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::KeyWord(const reqInfo *req, KeyWordDone done)
{
	auto *task = this->create_rpc_client_task("/KeyWord/KeyWord", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::KeyWord(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_KeyWord(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> TRPCClient::async_KeyWord(const reqInfo *req)
{
	using RESULT = std::pair<respInfo, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<respInfo>("/KeyWord/KeyWord", srpc::RPCAsyncFutureCallback<respInfo>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_KeyWord_task(KeyWordDone done)
{
	auto *task = this->create_rpc_client_task("/KeyWord/KeyWord", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("KeyWord")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("KeyWord")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::KeyWord(const reqInfo *req, KeyWordDone done)
{
	auto *task = this->create_rpc_client_task("KeyWord", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::KeyWord(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_KeyWord(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> TRPCHttpClient::async_KeyWord(const reqInfo *req)
{
	using RESULT = std::pair<respInfo, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<respInfo>("KeyWord", srpc::RPCAsyncFutureCallback<respInfo>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_KeyWord_task(KeyWordDone done)
{
	auto *task = this->create_rpc_client_task("KeyWord", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace KeyWord


namespace WebQuery
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void WebQuery(reqInfo *request, respInfo *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using WebQueryDone = std::function<void (respInfo *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void WebQuery(const reqInfo *req, WebQueryDone done);
	void WebQuery(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> async_WebQuery(const reqInfo *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_WebQuery_task(WebQueryDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void WebQuery(const reqInfo *req, WebQueryDone done);
	void WebQuery(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> async_WebQuery(const reqInfo *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_WebQuery_task(WebQueryDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void WebQuery(const reqInfo *req, WebQueryDone done);
	void WebQuery(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> async_WebQuery(const reqInfo *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_WebQuery_task(WebQueryDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void WebQuery(const reqInfo *req, WebQueryDone done);
	void WebQuery(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> async_WebQuery(const reqInfo *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_WebQuery_task(WebQueryDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void WebQuery(const reqInfo *req, WebQueryDone done);
	void WebQuery(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> async_WebQuery(const reqInfo *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_WebQuery_task(WebQueryDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("WebQuery")
{
	this->srpc::RPCService::add_method("WebQuery",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::WebQuery);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("WebQuery")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("WebQuery")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::WebQuery(const reqInfo *req, WebQueryDone done)
{
	auto *task = this->create_rpc_client_task("WebQuery", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::WebQuery(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_WebQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> SRPCClient::async_WebQuery(const reqInfo *req)
{
	using RESULT = std::pair<respInfo, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<respInfo>("WebQuery", srpc::RPCAsyncFutureCallback<respInfo>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_WebQuery_task(WebQueryDone done)
{
	return this->create_rpc_client_task("WebQuery", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("WebQuery")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("WebQuery")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::WebQuery(const reqInfo *req, WebQueryDone done)
{
	auto *task = this->create_rpc_client_task("WebQuery", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::WebQuery(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_WebQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> SRPCHttpClient::async_WebQuery(const reqInfo *req)
{
	using RESULT = std::pair<respInfo, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<respInfo>("WebQuery", srpc::RPCAsyncFutureCallback<respInfo>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_WebQuery_task(WebQueryDone done)
{
	return this->create_rpc_client_task("WebQuery", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("WebQuery")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("WebQuery")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::WebQuery(const reqInfo *req, WebQueryDone done)
{
	auto *task = this->create_rpc_client_task("WebQuery", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::WebQuery(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_WebQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> BRPCClient::async_WebQuery(const reqInfo *req)
{
	using RESULT = std::pair<respInfo, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<respInfo>("WebQuery", srpc::RPCAsyncFutureCallback<respInfo>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_WebQuery_task(WebQueryDone done)
{
	return this->create_rpc_client_task("WebQuery", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("WebQuery")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("WebQuery")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::WebQuery(const reqInfo *req, WebQueryDone done)
{
	auto *task = this->create_rpc_client_task("/WebQuery/WebQuery", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::WebQuery(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_WebQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> TRPCClient::async_WebQuery(const reqInfo *req)
{
	using RESULT = std::pair<respInfo, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<respInfo>("/WebQuery/WebQuery", srpc::RPCAsyncFutureCallback<respInfo>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_WebQuery_task(WebQueryDone done)
{
	auto *task = this->create_rpc_client_task("/WebQuery/WebQuery", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("WebQuery")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("WebQuery")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::WebQuery(const reqInfo *req, WebQueryDone done)
{
	auto *task = this->create_rpc_client_task("WebQuery", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::WebQuery(const reqInfo *req, respInfo *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_WebQuery(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<respInfo, srpc::RPCSyncContext>> TRPCHttpClient::async_WebQuery(const reqInfo *req)
{
	using RESULT = std::pair<respInfo, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<respInfo>("WebQuery", srpc::RPCAsyncFutureCallback<respInfo>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_WebQuery_task(WebQueryDone done)
{
	auto *task = this->create_rpc_client_task("WebQuery", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace WebQuery

